name = "mayz/otc"
version = "0.0.1"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "MAYZ OTC smart contracts for Catalyst"

[repository]
user = "MAYZGitHub"
project = "mayz-otc"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config]
